service: serverless
provider:
  name: aws
  runtime: nodejs12.x
  profile: ramirentuser
  region: us-east-1
  timeout: 30
  environment: ${file(../envs/dev.json)}

plugins:
    - serverless-sequelize-migrations

functions:
  UploadImage:
    handler: handler.uploadImage
    events:
      - s3:
          bucket: sourcebucket103
          event: s3:ObjectCreated:*
  ResizeImage:
    handler: handler.resizeImage

